---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/aSapien/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .zshrc-variables
  - .zshrc-aliases
  - .zshrc-functions
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - mas           # Mac App Store - CLI
  - htop-osx
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - git
  - bazel
  - maven
  - diff-so-fancy
  - autojump
  - fzf
  - jq
  - go
  - gpg
  - hub
  - httpie
  - sqlite
  - mcrypt        # crypto library
  - nmap          # port scanning, security auditing https://nmap.org
  - node
  - nvm
  - ssh-copy-id   # copy public key to remote machine's authorized_keys
  - readline      # Better terminal editing
  - openssl
  - tree
  - wget
  - wrk           # http benchmarking https://github.com/wg/wrk
  - tldr
  - openconnect   # Open client for Cisco AnyConnect VPN

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - bitwarden
  - alfred
  - notion
  - docker
  - firefox
  - google-chrome
  - sequel-pro
  - slack
  - telegram
  - sublime-text
  - visual-studio-code
  - vagrant
  - parallels
  - balenaetcher
  - dash
  - flour
  - beyond-compare
  - intellij-idea
  - java8
  - keybase
  - mailbutler
  - spotify
  - stremio
  - the-unarchiver
  - vlc
  - spectacle
  - ngrok
  - macdown
  - google-cloud-sdk
  - wireshark
  - amazon-photos
  - haptickey
  - tripmode
  - cleanmymac
  - flux

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835,  name: "Xcode" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
