---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: git@github.com:aSapien/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .localconfig.fish

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ammonite-repl # Scala REPL
  - autojump
  - dive          # Docker image explorer
  - fish          # Fish shell
  - fzf
  - git
  - go
  - httpie        # Like cURL with colored output
  - jq
  - kafka         # Kafka
  - mas           # Mac App Store - CLI
  - openssl
  - poetry        # Python environment management
  - scala
  - ssh-copy-id   # copy public key to remote machine's authorized_keys
  - tldr          # Explain commands and common
  - tree          # View directory tree
  - wget          

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - amazon-photos
  - balenaetcher
  - beyond-compare
  - bitwarden
  - brave-browser
  - burp-suite
  - dash
  - docker
  - firefox
  - flour
  - flux
  - google-cloud-sdk
  - intellij-idea
  - iterm2
  - java
  - karabiner-elements
  - kindle
  - macdown
  - ngrok
  - nomachine
  - notion
  - obsidian
  - odrive
  - parallels
  - paw
  - sequel-pro
  - slack
  - spectacle
  - spotify
  - steam
  - stremio
  - sublime-text
  - telegram
  - the-unarchiver
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - vscodium
  - wireshark
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835,  name: "Xcode" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
